version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: libheros_db
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASS}
    command: --init-file /data/app/init.sql
    volumes:
      - ./init.sql:/data/app/init.sql
      - ./data:/var/lib/mysql
